### ISSUE TITLE
TypeError: Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-automl#107]
The most basic usage of this library appears to be broken.  See the system test over here:
https://github.com/googleapis/nodejs-automl/pull/106/files

Running this gives the error:
```
 1) automl system tests
       should list all datasets:
     TypeError: Cannot read property 'charCodeAt' of undefined
      at peg$parsetemplate (node_modules/google-gax/build/src/path_template_parser.js:294:17)
      at Object.peg$parse [as parse] (node_modules/google-gax/build/src/path_template_parser.js:623:18)
      at new PathTemplate (node_modules/google-gax/src/path_template.ts:74:50)
      at segments.forEach.segment (node_modules/google-gax/src/path_template.ts:142:21)
      at Array.forEach (<anonymous>)
      at PathTemplate.render (node_modules/google-gax/src/path_template.ts:134:19)
      at AutoMlClient.locationPath (src/v1beta1/auto_ml_client.js:1634:53)
      at Context.it (system-test/automl.js:25:27)
```

The relevant code snippet is:

```js
const automl = require('@google-cloud/automl');
const client = new automl.AutoMlClient();
const location = 'us-central1';
const projectId = process.env.projectId;
const parent = client.locationPath(projectId, location);
client.listDatasets({parent}).then(console.log).catch(console.error);
```

**Comment by JustinBeckwith** [comment]
🤦‍♂️

**Comment by kinwa91** [comment]
What was up with this? I'm running into this problem locally..

**Comment by JustinBeckwith** [comment]
This is a really bad message from gax.  It happens when the projectId is undefined.

**Comment by alexychen2002** [comment]
How did you go about fixing this issue?

**Comment by neilsxD** [comment]
I'm still getting this error, pls help what should I do?

**Comment by JustinBeckwith** [comment]
Can you share what code you're trying?

**Comment by sebastijandumancic** [comment]
Hi all,

you should be able to resolve this issue by adding a fallback for project id like this: 
`const projectId = process.env.GCP_PROJECT || process.env.GCLOUD_PROJECT;`

**Comment by SwiftWinds** [comment]
> Hi all,
> 
> you should be able to resolve this issue by adding a fallback for project id like this:
> `const projectId = process.env.GCP_PROJECT || process.env.GCLOUD_PROJECT;`

Yeah, you can also type your actual projectId (which you get from the top left dropdown on the GCP console) with `const projectId = 'insert-project-name-here';`. According to [this](https://cloud.google.com/functions/docs/migrating/nodejs-runtimes), it seems that both `GCP_PROJECT` and `GCLOUD_PROJECT` environment variables are being retired in Node.js 10 runtimes, so I would lean on the safe side and just set projectId to the project ID string manually.
