### ISSUE TITLE
AutoML prediction bug on node js

### ISSUE THREAD

**Issue by zafark0695** [googleapis/nodejs-automl#143]
I used the node js to perform translation prediction on my custom model on google cloud. However i keep getting 2 problems 

1) SyntaxError: await is only valid in async function

So, i removed the await keyword and ran it again and then came error number 2

2) TypeError: Cannot read property 'payload' of undefined

My attempts to resolve was:

I added some console.log to see where the issue is occuring.

Based on my understanding of the code after i create a new prediction client instance, passing my model specs, it concatenates these specs into a full path to the model on the cloud.

Then it reads the file containing the text to translate locally then makes a request to the cloud  model by formatting it into a .json and fires a request to the model.

Then it receives a response back in a json format where the 2nd issue mentioned above( TypeError : Cannot read property 'payload' of undefined) occurs it cannot assign anything to payload as the response is undefined.

Hence i can't go on to see the translation.

The await keyword error (SyntaxError: await is only valid in async function)
i believe is the solution to it (because maybe the response was returning before the model could be loaded or the code is synchronous hence await was causing the error to wait for the response to return with data).

Can anyone help me on resolving these errors. Thanks for your time :)

Here is the link to error number 2 screenshot:
[TypeError: Cannot read property 'payload' of undefined](https://i.imgur.com/50ZJK24.png)

and here is the link to Google Cloud AutoML translation api (Step 5 is the translation)
[AutoML prediction](https://cloud.google.com/translate/automl/docs/tutorial#tutorial-translate-predict-nodejs)
#### Environment details

  - OS: Windows 10 version 1809
  - Node.js version: v10.15.3
  - npm version: 6.4.1
  - `@google-cloud/automl` version: v1beta1

**Comment by callmehiphop** [comment]
Because `predict` is an async function you'll either want to use `await` by wrapping it in an `async` function or you could use the `callback` version instead.

```js
client.predict({}, (err, response) => {
  response.payload.forEach(result => {});
});
```

The sample you're looking at is actually wrapped in an [`async function`](https://github.com/googleapis/nodejs-translate/blob/master/samples/automl/automlTranslationPredict.js#L26) but for whatever reason the cloud site does not reflect that.

@JustinBeckwith will something like this be resolved with the upcoming sample changes?

**Comment by zafark16** [comment]
@callmehiphop
The java snippet also gave this same cannot read property of payload undefined. However the python version is correct. I also noticed a few code updates and documentation not in sync to reflect the code illustrated. For example the set google account credentials syntax for the .json key file showed on that autoML documentation page is not valid i had to tweak it based on this video 

Link : https://youtu.be/tSnzoW4RlaQ

**Comment by callmehiphop** [comment]
@zafark0695 I can't speak to the Java snippet, you might want to open an issue over at [google-cloud-java](https://github.com/googleapis/google-cloud-java). Could you point me to the documentation that is not in sync?

**Comment by zafark16** [comment]
@callmehiphop
Step 7 and 8 under prerequisite section top of this page:
https://cloud.google.com/translate/automl/docs/tutorial

The gcloud auth login and iam policy binding

**Comment by callmehiphop** [comment]
Sadly I can't help there, but maybe @JustinBeckwith can point you in the right direction.

**Comment by zafark16** [comment]
@callmehiphop
I managed to fix it based on the youtube video above, but it would be great if they updated the doc so that other people does not have any issue setting up their credentials

**Comment by zafark0695** [comment]
@callmehiphop Hello man thank you for replying and you were right by wrapping the await inside of an async function the code now works thanks a lot man.  You are a saviour. :D

**Comment by zafark0695** [comment]
@callmehiphop  now on my linux VPS it says unhandled promise rejection. Here is more details about it:
`UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token
 in JSON at position 170
    at JSON.parse (<anonymous>)
    at ReadStream.inputStream.setEncoding.on.on.on (/var/www/html/node_modules/google-auth-library/build/src/auth/googleauth.js:346:39)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`


here is my code:
`  async function handler()
  {
	  try
	  {
			const responses = await client.predict
			({
				name: modelFullId,
				payload: payload,
				params: params
			});
			const response = responses[0];
			const ans = response.payload[0].translation.translatedContent.content;
			console.log(ans);
	  }
	  catch(err)
	  {
		  error(err);
	  }
  }
  function error(value) {
    if (console) {
        console.error(value)
    }
}`
I cannot see where it is failing, i tried putting the try catch alone, did not fix it. I modified it to add promise which im sure is where the problem is, because i had no idea on how to add promise on this scenario. On other examples promise was added differently. So please i need your help once again Dave. Thank you very much

**Comment by callmehiphop** [comment]
@zafark0695 that doesn't look like an issue with this client, but it does look like the underlying auth library is failing to read your key file. I would double check that the specified path is correct and that the file content is not malformed in anyway.

If that doesn't help, you might want to open an issue over at https://github.com/googleapis/google-auth-library-nodejs that demonstrates how you're authenticating the client.

**Comment by zafark0695** [comment]
I fixed it after a few hours of trying it, guess i should have tried a few
more times before i asked ya, sorry i wasted your time buddy. Thanks a lot
for your help Dave :D

**Comment by callmehiphop** [comment]
@zafark0695 no worries, glad to hear it's working!
