### ISSUE TITLE
Address all skipped tests and code style in the samples

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-automl#159]
In the run-up to GCP next, we made a concsious choice to let a few things slip in the samples and sample test code:
- [ ] Consistently use `async/await` instead of promises
- [ ] Use `execSync` over `execa` for execution
- [ ] Use `getProjectId()` instead of requiring the `GCLOUD_PROJECT` env var

We need to come back around and clean all of these up.

**Comment by callmehiphop** [comment]
There are a number of sample PRs open right now, I'm guessing this work should be done after they're merged in?

**Comment by JustinBeckwith** [comment]
Yeah.  We're in the crunch here for GCP Next, and these samples get merged into the docs.  We are making a choice to land this, then fix after the fact.  You know me.  I promise this won't become a habit 🙃

**Comment by beccasaurus** [comment]
We'll TAL at this, we need to author a set of tests for AutoML code samples across the board (all languages) which aren't flaky and complete in a reasonable amount of time & help guarantee working samples

**Comment by beccasaurus** [comment]
I removed the sample testing to #161 

Y'all can take full ownership of this regarding code style guidelines etc.

Please pull in @googleapis/ml-apis for product-relating issues. Thanks!

**Comment by czahedi** [comment]
Dupicate of https://github.com/googleapis/nodejs-automl/issues/161
