### ISSUE TITLE
Replace AutoML test with tests for each sample which execute (not skipped)

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/nodejs-automl#161]
Every code sample should have a corresponding test which is not skipped, as much as possible.

In cases where a code sample runs a long-running operation, this may mean that the cloud.google.com code sample may be extended to include a cancellation.

Alternatively, the test can cancel the operation after it has been started.

Operations which run in a reasonable amount of time should be executed, e.g. anything which takes < 1 minute to execute (as an example)

**Comment by beccasaurus** [comment]
@googleapis/ml-apis

**Comment by czahedi** [comment]
Noah/Torry how are these tests going?

**Comment by nnegrey** [comment]
That depends... 
GA samples: yes, done
Beta samples: no, untouched (can't delete cus of reliance from localization docs)
