### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'google/cloud/automl/v1beta1/prediction_service.proto'

### ISSUE THREAD

**Issue by cmaycumber** [googleapis/nodejs-automl#226]
#### Environment details

  - OS: OSx
  - Node.js version: 8.10
  - Yarn: 1.17.3
  - `@google-cloud/automl` version: 1.2.4

The end goal will be running @google-cloud/automl inside of an AWS lambda but I'm currently running into this issue while testing locally using the serverless js framework.

#### Steps to reproduce

  1. Intialize the client with 
```
const client = new automl.v1beta1.PredictionServiceClient();
```
2. Returns the following error:
```
There was an error making predictions on the links { Error: ENOENT: no such file or directory, open 'google/cloud/automl/v1beta1/prediction_service.proto'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at fetch (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/node_modules/protobufjs/src/root.js:160:34)
    at Root.load (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/node_modules/protobufjs/src/root.js:194:13)
    at Root.loadSync (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/node_modules/@grpc/proto-loader/build/src/index.js:230:27)
    at GrpcClient.loadFromProto (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/node_modules/google-gax/build/src/grpc.js:118:44)
    at GrpcClient.loadProto (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/node_modules/google-gax/build/src/grpc.js:150:21)
    at new PredictionServiceClient (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/.webpack/service/functions/prospector.js:4084:28)
    at Object.<anonymous> (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/.webpack/service/functions/prospector.js:187:24)
    at Generator.next (<anonymous>)
    at /Users/cmaycumber/Documents/backlink/Backlink-Prospector/.webpack/service/functions/prospector.js:99:71
    at new Promise (<anonymous>)
    at module.exports.__awaiter (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/.webpack/service/functions/prospector.js:95:12)
    at makePredictions (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/.webpack/service/functions/prospector.js:182:60)
    at Object.<anonymous> (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/.webpack/service/functions/prospector.js:315:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/cmaycumber/Documents/backlink/Backlink-Prospector/.webpack/service/functions/prospector.js:96:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'google/cloud/automl/v1beta1/prediction_service.proto' }
```

Any help in solving this would be great.

**Comment by callmehiphop** [comment]
@alexander-fenster I'm still a little fuzzy on how the proto/json changes work, but would that potentially fix this? I'm sort of assuming we no longer load the proto files, but instead a JSON file - which I'm guessing can be done via `require`?

**Comment by alexander-fenster** [comment]
@callmehiphop It might fix it. In Node.js, JSON protos work pretty much in the same way as opening regular proto files - it is being passed to `protobufjs.loadSync` as a file and is opened with `fs.readFileSync`. It still simplifies the process since only one file is loaded and no runtime parsing is performed.

JSON protos are loaded with `require` for gRPC-fallback ("browser") use case. You can check the updated client code following the logic of `fallback` parameter. I will write a doc on that later.

**Comment by callmehiphop** [comment]
👋 @cmaycumber would you be willing to re-test this with the latest version of the library?

**Comment by cmaycumber** [comment]
@callmehiphop Yes for sure! I'll test it and let you guys know

**Comment by cmaycumber** [comment]
@callmehiphop I tried creating the client with the same code as my previous comment and took directly from the updated docs using @google-cloud/automl v1.5.0:
```
const automl = require('@google-cloud/automl');

const client = new automl.PredictionServiceClient();
```
It looks like I'm running into the same error:
```
{ Error: ENOENT: no such file or directory, open 'protos.json'
```

**Comment by alexander-fenster** [comment]
@cmaycumber That's interesting. It looks like regular `fs.readFileSync` fails for some reason. I have two options for you :)

1. Please try adding a fallback option to a constructor:

```js
const client = new automl.PredictionServiceClient({fallback: true});
```
and let us know if it works. If it does, feel free to use this option. It changes the internal way of sending requests and getting responses (it will use HTTP/1 instead of gRPC). One caveat is that you'll need to use integer constants for all enum values in your request objects (e.g. use 1 instead of `INCH`, and so on - as specified in [this file](https://github.com/googleapis/nodejs-automl/blob/master/protos/protos.json)).

2. I made a slightly modified version of the client library to GitHub branch that logs some information using `console.log`. Can I ask you to update your `package.json` to use

```
  "@google-cloud/automl": "googleapis/nodejs-automl#absolute-path"
```
(it directs `npm` to take it directly from my GitHub branch), try running your code (with no `fallback` option), and post whatever is logged here?

Thank you so much for helping us debug this!

**Comment by alexander-fenster** [comment]
@cmaycumber Oh, I actually misread your original message. I was under impression this happens with AWS Lambda but now I see you're talking about some serverless JS framework. Can you give us more details about what kind of framework it is? Do you know if Node.js `fs` module is available at all there?

If there is no `fs`, then my `fallback` option (#1 above) should help you, and will likely be the only available option at this time. You might face some issues with authentication, I'll be happy to help you with that if it happens.

Please let us know!

**Comment by cmaycumber** [comment]
@alexander-fenster Sure, it is essentially a framework to develop serverless functions in different cloud platforms. Here is the link: https://serverless.com/. You create a yaml file that allows you to deploy serverless functions to different cloud providers, I'm using a plugin that emulates the cloud environment to test my lambda functions locally before pushing them.

It looks like the fallback is working right now. It looks right you are right, I'm getting a 401 response. I don't have a lot of time to fix it right now but any if you have any suggestions on how to fix the auth I'll implement that asap

**Comment by cmaycumber** [comment]
Great product btw and I really appreciate all the support.

**Comment by alexander-fenster** [comment]
From what you said (401 response), does it mean you're using `@google-cloud/automl` in the front-end setting (browser JavaScript code)? If so, you'll need to implement the whole OAuth2 workflow to authenticate the user against Google services. I can make an example but before we do that, let's figure out if it's what we really want to do.

If you can move the library usage to the server-side Node.js part, and authenticate using a service account key, it should just work (even without the fallback option).

**Comment by cmaycumber** [comment]
@alexander-fenster No, I'm not using it in the frontend. I'm currently trying to authenticate via a google_credentials.json file. Originally, I planned on using fetch to just hit the normal endpoint that is shown in the curl example, but when I tried in the cmd line I received a message that this type of auth is no longer supported and I should use a service account then I switched over to the node library and the credentials file for auth.

The lambda code is being bundled by webpack so that I can gain additional features creating my serverless functions. Maybe this has an impact on the auth?

**Comment by alexander-fenster** [comment]
> The lambda code is being bundled by webpack so that I can gain additional features creating my serverless functions. 

It does! It actually breaks anything completely :(

So, your setup is like this:

```
|
+-- package.json
+-- webpack.config.js
+-- src
        +-- index.js
+-- node_modules
        +-- @google-cloud
                   +-- automl
```

then you're webpacking the whole thing setting Node.js as a target, and run the script from the resulting bundle?

If I got the use case correctly, let me play with this use case. I'm guessing it must be a small fix to make this work.

**Comment by alexander-fenster** [comment]
@cmaycumber Can you share the `webpack.config.js` you use?

**Comment by cmaycumber** [comment]
Yeah, will do. @alexander-fenster  
```
const path = require('path');
const slsw = require('serverless-webpack');
const WebpackPluginCopy = require('copy-webpack-plugin');

module.exports = {
  mode: 'none',
  entry: slsw.lib.entries,
  plugins: [
    new WebpackPluginCopy([
      {
        from: `./google_credentials.json`,
      },
    ]),
  ],
  resolve: {
    extensions: ['.js', '.json', '.ts'],
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  externals: [
    {
      'socket.io': 'socket.io',
    },
    /^[a-z\-0-9]+$/,
  ],
  target: 'node',
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: 'ts-loader',
          },
        ],
      },
    ],
  },
};
```

**Comment by cmaycumber** [comment]
@alexander-fenster I got it working. The auth error was a mistake on my end(I left some previous code from trying another workaround in there), the fallback seems to fix the issue when working with auth through the service account. Thanks again for all the help.

**Comment by alexander-fenster** [comment]
@cmaycumber Nice! Thank you for your update.
