### ISSUE TITLE
One file per sample

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/nodejs-automl#233]
Please split large files (for example [/samples/vision/automlVisionDataset.js](https://github.com/googleapis/nodejs-automl/blob/master/samples/vision/automlVisionDataset.js)) that contain more than one sample into small files that contain a single sample per file. 

See @bcoe's [comment](https://github.com/googleapis/nodejs-automl/pull/225#pullrequestreview-284311645): 

> A note for future improvements, the template we use for generating `samples/README.md` and `README.md` currently assumes there's one sample per-file. If we eventually split the samples across multiple files, we'll end up with a nicer corresponding table in `README.md` -- I don't see this as a blocker, but it would be good to create a tracking issue for someone to pick up 😄

**Comment by callmehiphop** [comment]
Could be wrong, but I thought the ML team was working on making this happen?

**Comment by anguillanneuf** [comment]
@callmehiphop Would you know who on the ML team?

**Comment by callmehiphop** [comment]
Paging @beccasaurus!

**Comment by czahedi** [comment]
Noah correct me if I'm wrong but the refactor of the AutoML samples makes this issue obsolete? We moved to having several samples supported by a single file for ease of maintenance and testing.

**Comment by nnegrey** [comment]
I have multiple PRs open, once those get merged, I can update docs, once all the docs are merged, I can go delete the samples. Gonna be a long process though

**Comment by czahedi** [comment]
Checking in here - did those PRs get merged?

**Comment by nnegrey** [comment]
Yea, samples won't be deleted till localized pages are updated.
