### ISSUE TITLE
IAM get permission error to input bucket even when input bucket is public

### ISSUE THREAD

**Issue by johnbalvin** [googleapis/nodejs-automl#254]
#### Summary
 I'm making a batchPrediction with the input file's bucket being public, but I'm getting this error:

> Error: 9 FAILED_PRECONDITION: Service account account `[xxxx]@gcp-sa-automl.iam.gserviceaccount.com` does not have `[storage.buckets.get]` IAM permission to the input bucket. Please either copy the files to the Google Cloud Storage bucket owned by the model owner project

#### sample code
```
const automl = require('@google-cloud/automl');
const client = new automl.PredictionServiceClient();
const automlModel= client.modelPath('project_id','zone','model_id');
const input="gs://[bucketname]/images/info.csv"
const output="gs://[bucketname]/images/output"
try{
          responses = await client.batchPredict({
              name: automlModel,
              inputConfig: {gcsSource:{inputUris:[input]}},
              outputConfig: {gcsDestination:{outputUriPrefix:output}},
          }).then(resp=>{
              const [operation, initialApiResponse] = resp;
              console.log("initialApiResponse: ",initialApiResponse);
              return operation.promise();
          });
}catch(err){
          console.log(err);
 }
```
#### Environment details 

  - OS: Container-Optimized OS   <- I'm using a docker image 
  - Node.js version: v12.11.0
  - npm version: 6.11.3
  - `@google-cloud/automl` version: 1.7.2

#### Steps to reproduce

  1. create a public bucket, save images to make a prediction and save the csv file for batch predictions in it
  2. make a batchPrediction with the input file being the path of the csv file in step 1

**Comment by bcoe** [comment]
@leahecole any thoughts on this issue, at a glance it seems like a permission issue.

**Comment by leahecole** [comment]
+1 to the at a glance it seems like a permissions issue, but I'll try to replicate.

**Comment by leahecole** [comment]
Hi @johnbalvin - still going to take a look at this but I also have a question for one theory I'm going to investigate - do you know if you have [bucket policy only](https://cloud.google.com/storage/docs/bucket-policy-only) enabled on the bucket you're using?

**Comment by johnbalvin** [comment]
hi @leahecole  indeed I have "bucket-level IAM policy." 
it has view for permission for everyone
![image](https://user-images.githubusercontent.com/25888114/67915161-2e13ea00-fb60-11e9-915a-87bdf953baa5.png)

**Comment by leahecole** [comment]
Awesome - that image is very helpful. I trained a model today to use for comparison, and will try to replicate today (10/31)  or tomorrow.

**Comment by Ark-kun** [comment]
@leahecole Do you have any success? I have the same issues with AutoML and GCS. I've tried both ULA and fine-grained access, but still have this issue.

**Comment by leahecole** [comment]
Hi @Ark-kun - I haven't worked with this library in awhile, so I'm actually going to pass it off to one of my colleagues who I'm hoping may have seen something like this more recently!

**Comment by leahecole** [comment]
@feywind - any insight here, or can you reroute to someone who has touched node more recently than I?

**Comment by feywind** [comment]
`Error: 9 FAILED_PRECONDITION` really sounds like a server-side error rather than a library error. Let me see if I can figure out who to route this to in AutoML.

**Comment by frankyn** [comment]
| Error: 9 FAILED_PRECONDITION: Service account account [xxxx]@gcp-sa-automl.iam.gserviceaccount.com does not have [storage.buckets.get] IAM permission to the input bucket. Please either copy the files to the Google Cloud Storage bucket owned by the model owner project

This is related to `[xxxx]@gcp-sa-automl.iam.gserviceaccount.com` not having `storage.buckets.get` permission which is under `roles/storage.admin` at least on the bucket `[bucketname]`.

Based on the example provided, you will need to grant `roles/storage.admin` at least at the bucket level for `[xxxx]@gcp-sa-automl.iam.gserviceaccount.com` for the API to succeed.

**Comment by munkhuushmgl** [comment]
I am closing this issue. Feel free to reopen if you are still experiencing the same issue.
