### ISSUE TITLE
Can't get status of a batch predict operation  "Location ID was not provided"

### ISSUE THREAD

**Issue by johnbalvin** [googleapis/nodejs-automl#255]
#### Summary

I'm trying to get the status of a batch operation like in this [tutorial](https://cloud.google.com/vision/automl/docs/predict-batch#automl_vision_batch_predict-nodejs)

but I always get the error:

> 'List of found errors:\t1.Field: name; Message: Location ID was not provided.\t2.Field: name; Message: Required field is invalid\t

![image](https://user-images.githubusercontent.com/25888114/67194461-c40b8000-f3bc-11e9-8d87-61d2fda5efa7.png)

#### Sample code
```
//making the the batch prediction
const automlModel= client.modelPath('project_id','zone','model_id');
const client = new automl.PredictionServiceClient();
let jobName="";
 try{
            jobName = await client.batchPredict({
                name: automlModel,
                inputConfig: {gcsSource:{inputUris:inputs}},
                outputConfig: {gcsDestination:{outputUriPrefix:output}},
            }).then(resp=>{
                const [operation, initialApiResponse] = resp;
                return initialApiResponse.name;
            });
     }catch(err){
            consoloe.log(err);
     }
//------
//later on the code
const clientAutoML = new automl.AutoMlClient();
  let response = "";
  try{
       [response] = await clientAutoML.operationsClient.getOperation(jobName);
   }catch(err){
      console.log(err); //I GET THE ERROR HERE
   } 
//----------
```

#### Environment details

  - OS: windows 10
  - Node.js version: v12.11.0  
  - npm version: 6.11.3
  - `@google-cloud/automl` version: 1.7.2

#### Steps to reproduce

  1. Create a batch prediction and get it's name
  2. Get status of the batch prediction

**Comment by callmehiphop** [comment]
👋 @johnbalvin I'm trying to hunt this down and it looks like you might need to pass the job name in through an object. Would you mind trying out the following?

```js
clientAutoMl.operationsClient.getOperation({name: jobName});
```
