### ISSUE TITLE
SyntaxError: Identifier 'projectId' has already been declared

### ISSUE THREAD

**Issue by oofin008** [googleapis/nodejs-automl#262]
#### Environment details

  - OS: Window 10
  - Node.js version: v12.13.0
  - npm version: 6.12.0
  - `@google-cloud/automl` version: 1.7.3

#### Steps to reproduce

  1. in folder samples, run "npm install"
  2. edit quickstart.js in todo list.
  3. save and run "node quickstart.js"
![image](https://user-images.githubusercontent.com/33728581/68362269-4b951500-0159-11ea-8e4c-7de4b042a3ba.png)

**Comment by bcoe** [comment]
@oofin008 you should be able to run the `quickstart.js` as is, and the arguments you pass to the command line will be set in the `projectId` variable, the variables in comments are for reference if you're pulling the code out into another application (rather than running the sample directly).
