### ISSUE TITLE
The provided location ID is not valid

### ISSUE THREAD

**Issue by sugendran** [googleapis/nodejs-automl#263]
I've just created a new natural language model which is in the `eu` region. When I try to use the client I get the following Error:

```
3 INVALID_ARGUMENT: List of found errors: 1.Field: name; Message: The provided location ID is not valid.
Error: 3 INVALID_ARGUMENT: List of found errors:	1.Field: name; Message: The provided location ID is not valid.	
    at Object.callErrorFromStatus (/Users/sugendran/code/getmployd-ml/bulk-classifier/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.<anonymous> (/Users/sugendran/code/getmployd-ml/bulk-classifier/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:215:7)
    at /Users/sugendran/code/getmployd-ml/bulk-classifier/node_modules/@grpc/grpc-js/build/src/call-stream.js:75:22
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

The model path is `projects/305312444325/locations/eu/models/TCN8963992845815906304` 

and I'm using `eu` as the location when calling .modelPath

#### Environment details

  - OS: OSX
  - Node.js version: v12.12.0
  - npm version: 6.11.3 
  - `@google-cloud/automl` version: 1.7.3

#### Steps to reproduce
  -  Create a new natural language model in the EU region and try to use it.

**Comment by sugendran** [comment]
btw: I ended up using the python sdk instead.

**Comment by bcoe** [comment]
👍 sorry you bumped into this, I'm glad you found a reasonable workaround; Please don't hesitate to reopen an issue if you move back to the Node.js client, and want help digging into issues.

**Comment by sugendran** [comment]
I would actually like to use the node.js client. I couldn't work out where the issue was coming from - I can only assume it's a validation error in the proto/grpc somewhere.

**Comment by XinyueZ** [comment]
I have the same issue https://github.com/googleapis/nodejs-automl/issues/411
