### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nicobrinkkemper** [googleapis/nodejs-automl#269]
Currently there is no npm package called `@types/google-cloud__automl`
This could enhance the experience users have with the library. Since other google cloud package feature typescript support also, it makes sense to create this npm package.

**Comment by callmehiphop** [comment]
👋 @nicobrinkkemper you'll be happy to hear that there is currently an effort to add TypeScript support to all of the client libraries.

**Comment by JustinBeckwith** [comment]
This package is now written with TypeScript, and ships its own types :)  Enjoy!
