### ISSUE TITLE
Google AutoML Error - Error: 4 DEADLINE_EXCEEDED: Deadline exceeded

### ISSUE THREAD

**Issue by soubhikchatterjee** [googleapis/nodejs-automl#289]
#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: v11.15.0
  - npm version: 6.13.2
  - `@google-cloud/automl` version: 1.10.0

#### Steps to reproduce

I am using the [nodejs library][1] to import data to the dataset using the following code.

    require("dotenv").config();
    const automl = require("@google-cloud/automl");
    const client = new automl.v1beta1.AutoMlClient();
    
    (async () => {
      const projectId = `xxx`;
      const computeRegion = `us-central1`;
      const datasetId = `xxx`;
      const path = "gs://example_bucket_ocr_idr2/happiness.csv";
    
      // Get the full path of the dataset.
      const datasetFullId = client.datasetPath(projectId, computeRegion, datasetId);
    
      let inputConfig = {};
      if (path.startsWith(`bq`)) {
        // Get Bigquery URI.
        inputConfig = {
          bigquerySource: {
            inputUri: path
          }
        };
      } else {
        // Get the multiple Google Cloud Storage URIs.
        const inputUris = path.split(`,`);
        inputConfig = {
          gcsSource: {
            inputUris: inputUris
          }
        };
      }
    
      // Import the dataset from the input URI.
      client
        .importData({ name: datasetFullId, inputConfig: inputConfig })
        .then(responses => {
          const operation = responses[0];
          console.log(`Processing import...`);
          return operation.promise();
        })
        .then(responses => {
          // The final result of the operation.
          const operationDetails = responses[2];
    
          // Get the data import details.
          console.log("Data import details:");
          console.log(`\tOperation details:`);
          console.log(`\t\tName: ${operationDetails.name}`);
          console.log(`\t\tDone: ${operationDetails.done}`);
        })
        .catch(err => {
          console.error(err);
        });
    })();

But every time I run it, I get ***DEADLINE_EXCEEDED*** error. I have searched for a solution but didnt find any till now. 

    { Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
        at Object.callErrorFromStatus (/var/www/html/test/google-ml/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
        at Http2CallStream.call.on (/var/www/html/test/google-ml/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
        at Http2CallStream.emit (events.js:198:15)
        at process.nextTick (/var/www/html/test/google-ml/node_modules/@grpc/grpc-js/build/src/call-stream.js:79:22)
        at processTicksAndRejections (internal/process/task_queues.js:79:9)
      code: 4,
      details: 'Deadline exceeded',
      metadata: Metadata { internalRepr: Map {}, options: {} } }

  [1]: https://www.npmjs.com/package/@google-cloud/automl

The *happiness.csv* file has the following contents:

    gs://example_bucket_ocr_idr2/certs/01.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/02.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/03.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/04.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/05.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/06.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/07.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/08.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/09.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/10.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/11.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/12.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/13.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/14.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/15.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/16.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/17.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/18.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/19.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/20.pdf, certificates, post_graduation
    gs://example_bucket_ocr_idr2/certs/21.pdf, certificates, post_graduation

Any help will be appreciated!

**Comment by bcoe** [comment]
@alexander-fenster any thoughts with regard to this issue? Is there a way to extend timeout before `DEADLINE_EXCEEDED` is fired, or would this need to be broken into more requests (I would expected this to be batched into multiple API requests already).

**Comment by alexander-fenster** [comment]
@soubhikchatterjee One thing to try here would be to increase the timeout manually and see if it helps.  Could you try opening `node_modules/@google-cloud/automl/src/v1/auto_ml_client_config.json` and, in the following block:

```json
        "ImportData": {
          "timeout_millis": 20000,
          "retry_codes_name": "non_idempotent",
          "retry_params_name": "default"
        },
```

set the `timeout_millis` to something more than 20 seconds?  It may or may not help, but let's start from here.

**Comment by soubhikchatterjee** [comment]
Hello Guys

Thanks for adding replies to this thread, turns out that I was trying to import multi-labeled csv file to a single label dataset. I changed the csv and added just one label in each row.

But this error message is too deceptive. Can this be fixed?

**Comment by bcoe** [comment]
@soubhikchatterjee 👍I'm glad you got things worked out. I'll see if I can pass your feedback on to the appropriate person (about this being confusing, and needing some more documentation).

**Comment by soubhikchatterjee** [comment]
@alexander-fenster For some files I am still getting the "deadline ..." error, so when i increased the timeout as per your suggestion, it fixed the issue. Is there I can over-ride this value from my nodejs code instead of modifying the files inside the node_modules ?

Many thanks in advance.

**Comment by soubhikchatterjee** [comment]
@bcoe Could you please help me with the query posted above?

Thanks in advance

**Comment by alexander-fenster** [comment]
@soubhikchatterjee It should be possible to override config values by passing the same JSON object to the client constructor as `clientConfig`:

```js
const fs = require('fs');
const path = require('path');
const automl = require('@google-cloud/automl');

const clientConfig = JSON.parse(
  fs.readFileSync(
    path.join(
      require.resolve('@google-cloud/automl'), 
      '..', 
      'v1beta1',   // or 'v1'
      'auto_ml_client_config.json'
    )
  )
);

// make fixes to the config
clientConfig.interfaces['google.cloud.automl.v1beta1.AutoMl']
  .methods.ImportData.timeout_millis = 500000;

// pass it as a parameter
const client = new automl.v1beta1.AutoMlClient({ clientConfig });
```

Please let us know if it works for you!

**Comment by soubhikchatterjee** [comment]
@alexander-fenster Works like a charm! Thanks for the code.

I have 2 questions though:

1) If the imports take so much time, why is the default timeout in the config file set to such a lower value?

2) During the time when the nodejs code is running the import process, if my VPS shuts-down or if my node process terminates for any reason, what will be the impact of the import process? will the google apis continue to import it at their end or do i have to reinitiate the import process?

**Comment by alexander-fenster** [comment]
@soubhikchatterjee For your first question, the tricky thing here is that this client library is auto-generated based on the [configuration](https://github.com/googleapis/googleapis/blob/ad6e508d0728e1d1bca6e3f328cd562718cb772d/google/cloud/automl/v1beta1/automl_gapic.yaml#L330-L351) provided by API developers, so I cannot really answer why this particular default timeout value was chosen. @bcoe maybe you can followup with the API team? It makes sense for me to increase the default timeout for the Import operation.

For your second question, I think anything cannot be guaranteed in this case. The client library sends your data over gRPC channel (HTTP2 connection) and if the connection is suddenly dropped, I can imagine all the possible outcomes :)  I think reinitiating the import process will be the safest option for you in this case.

**Comment by soubhikchatterjee** [comment]
Thank you @alexander-fenster for your reply.

**Comment by nnegrey** [comment]
On number 2: if you are using a .csv file hosted in GCS then no you don't need to wait for the operation to complete. The API will get your request and start importing everything hosted on GCS. So you could fire and forget and just check back on the operation status later with the operation Id. 

To get the status of the operation you can use this sample: https://github.com/googleapis/nodejs-automl/blob/master/samples/get_operation_status.js

**Comment by bitcoinvsalts** [comment]
I am also getting some DEADLINE_EXCEEDED: Deadline exceeded errors.

I am using `"@google-cloud/automl": "^2.5.1",`

Here is my code:

`
const client = new automl.v1beta1.PredictionServiceClient()
const modelFullId = client.modelPath(projectId, computeRegion, modelId)

client.predict({
    name: modelFullId,
    payload: inputs,
    params: {feature_importance: false}
})
.then( async responses => {
`
