### ISSUE TITLE
Training an existing model

### ISSUE THREAD

**Issue by soubhikchatterjee** [googleapis/nodejs-automl#313]
I have been spending a lot of time lately to learn if and how it is possible to train an existing model with an existing dataset. Meaning that I have a csv file that I have imported to an existing dataset but when I want to train a model, it creates a new model every time I run the training script.

Below is the script I am using and as you can see, it creates a new model after the training instead of using an existing one. Can someone please tell me how to do it?

```
const automl = require(`@google-cloud/automl`);

const client = new automl.v1beta1.AutoMlClient();

const projectId = `xxx`;
const computeRegion = `us-central1`;
const datasetId = `xxx`;
const modelName = `myModel2`;

(async () => {
  // A resource that represents Google Cloud Platform location.
  const projectLocation = client.locationPath(projectId, computeRegion);

  // Set model name and model metadata for the dataset.
  const myModel = {
    displayName: modelName,
    datasetId: datasetId,
    textClassificationModelMetadata: {}
  };

  // Create a model with the model metadata in the region.
  const [operation, initialApiResponse] = await client.createModel({
    parent: projectLocation,
    model: myModel
  });
  console.log(`Training operation name: ${initialApiResponse.name}`);
  console.log(`Training started...`);
  const [model] = await operation.promise();
  // Retrieve deployment state.
  let deploymentState = ``;
  if (model.deploymentState === 1) {
    deploymentState = `deployed`;
  } else if (model.deploymentState === 2) {
    deploymentState = `undeployed`;
  }

  // Display the model information.
  console.log(`Model name: ${model.name}`);
  console.log(`Model id: ${model.name.split(`/`).pop(-1)}`);
  console.log(`Model display name: ${model.displayName}`);
  console.log(`Model create time:`);
  console.log(`\tseconds: ${model.createTime.seconds}`);
  console.log(`\tnanos: ${model.createTime.nanos}`);
  console.log(`Model deployment state: ${deploymentState}`);
})();

```

**Comment by soubhikchatterjee** [comment]
@alexander-fenster  @bcoe 

Could you please help me with the above query? I have been struggling to get this done. 

Many thanks in advance.

**Comment by alexander-fenster** [comment]
@bcoe This is more about API usage, not about the generated library itself - can you follow up with the API team?

**Comment by bcoe** [comment]
@nnegrey any thoughts on this one, I know you've contributed a bit to this library.

**Comment by nnegrey** [comment]
AutoML doesn't support Transfer Learning from an existing model.

Also `display_name` is not a unique field, to specify an existing model, you'd need the `model_id`, but that is an output only field as specified here in the docs:
https://cloud.google.com/automl/docs/reference/rpc/google.cloud.automl.v1#google.cloud.automl.v1.Model

**Comment by soubhikchatterjee** [comment]
Thanks @nnegrey for your inputs.

@alexander-fenster  @bcoe So to summarise, currently there is no way we can train an existing model, yes?

 
Thanks
