### ISSUE TITLE
The provided location ID is not valid

### ISSUE THREAD

**Issue by rake146** [googleapis/nodejs-automl#314]
I'm currently experiencing an issue when using this package.
I've created a new EU model and when trying to use it. Despite using the 'eu' location ID, i'm still seeing this issue.

(node:8904) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: List of found errors:  1.Field: name; Message: The provided location ID doesn't match the endpoint. For automl.googleapis.com, the valid location ID is `us-central1`. For eu-automl.googleapis.com, the valid location ID is `eu`.

#### Environment details

  - OS: Windows 
  - Node.js version: v12.14.0
  - `@google-cloud/automl` version: 1.10.0

#### Steps to reproduce

  1. Create a new model with project settings as 'EU' then try use it.

Thanks!

**Comment by bcoe** [comment]
@rake146 my expectation would be that the location ID would be one of the regions in this list:

https://cloud.google.com/compute/docs/regions-zones/

So, `europe-west1`, `europe-west2`, etc, have you tried this?

**Comment by rake146** [comment]
Yes I've tried both and it says only 'EU' and 'us-central1' are valid

**Comment by nnegrey** [comment]
Hi, are you using automl v1 or v1beta1?

**Comment by nnegrey** [comment]
Also which automl product?

**Comment by telpirion** [comment]
Did you happen to use 'EU' or 'eu' in your requests?

**Comment by cvielma** [comment]
I'm also having this issue from java client. I'm starting the client this way:

**Comment by cvielma** [comment]
Fixed it initializing it like this:
