### ISSUE TITLE
How to pass the value as Google cloud Storage URI in vision_classification_predict.js

### ISSUE THREAD

**Issue by Anuradha677** [googleapis/nodejs-automl#328]
Here, in filePath, I am giving the gcs bucket URI like below.
```
   const filePath = 'gs://buckettest/user/userface.jpg';
     // Imports the Google Cloud AutoML library
    const {PredictionServiceClient} = require(`@google-cloud/automl`).v1;
    const fs = require(`fs`);

  // Instantiates a client
  const client = new PredictionServiceClient();

  // Read the file content for translation.
  const content = fs.readFileSync(filePath);

  async function predict() {
    // Construct request
    // params is additional domain-specific parameters.
    // score_threshold is used to filter the result
    const request = {
      name: client.modelPath(projectId, location, modelId),
      payload: {
        image: {
          imageBytes: filePath,
        },
      },
    };

    const [response] = await client.predict(request);

    for (const annotationPayload of response.payload) {
      console.log(`Predicted class name: ${annotationPayload.displayName}`);
      console.log(
        `Predicted class score: ${annotationPayload.classification.score}`
      );
    }
  }

  predict();
```
If I am using payload something like this. I am getting an error `"INVALID_ARGUMENT: List of found errors: 1.Field: payload.payload; Message: Required field not set."`

If i am using the local file as mentioned in vision_classification_predict.js there is no issue.
```
payload: {
            inputConfig: {
                gcsSource: {
                  inputUris: [filePath],
                },
              },
```
Please help me with this. I am new to these APIs.

**Comment by nnegrey** [comment]
You can't pass `inputUris` to the v1 API. 
https://cloud.google.com/automl/docs/reference/rpc/google.cloud.automl.v1#google.cloud.automl.v1.Image

**Comment by shirishbmc** [comment]
> Here, in filePath, I am giving the gcs bucket URI like below.
> 
> ```
>    const filePath = 'gs://buckettest/user/userface.jpg';
>      // Imports the Google Cloud AutoML library
>     const {PredictionServiceClient} = require(`@google-cloud/automl`).v1;
>     const fs = require(`fs`);
> 
>   // Instantiates a client
>   const client = new PredictionServiceClient();
> 
>   // Read the file content for translation.
>   const content = fs.readFileSync(filePath);
> 
>   async function predict() {
>     // Construct request
>     // params is additional domain-specific parameters.
>     // score_threshold is used to filter the result
>     const request = {
>       name: client.modelPath(projectId, location, modelId),
>       payload: {
>         image: {
>           imageBytes: filePath,
>         },
>       },
>     };
> 
>     const [response] = await client.predict(request);
> 
>     for (const annotationPayload of response.payload) {
>       console.log(`Predicted class name: ${annotationPayload.displayName}`);
>       console.log(
>         `Predicted class score: ${annotationPayload.classification.score}`
>       );
>     }
>   }
> 
>   predict();
> ```
> 
> If I am using payload something like this. I am getting an error `"INVALID_ARGUMENT: List of found errors: 1.Field: payload.payload; Message: Required field not set."`
> 
> If i am using the local file as mentioned in vision_classification_predict.js there is no issue.
> 
> ```
> payload: {
>             inputConfig: {
>                 gcsSource: {
>                   inputUris: [filePath],
>                 },
>               },
> ```
> 
> Please help me with this. I am new to these APIs.
@nnegrey - Do you have any sample code for this  ? if yes please share
