### ISSUE TITLE
GCP AutoML dataset id return from Node.js client library is mismatched the actual dataset id.

### ISSUE THREAD

**Issue by SanyapongYoukachen** [googleapis/nodejs-automl#360]
Previously, i can use node.js automl to create dataset, import data and training the model successfully. But now i faced  "Error: 5 NOT_FOUND: The Dataset doesn't exist or is inaccessible for use with AutoML".

After that, i realized that the dataset id return from create dataset request is mismatched the actual dataset id (compared with web interface). 

Any update am i missing? or do i missed something? 

#### Environment details

  - OS: Ubuntu 18.04 LTS
  - Node.js version: v12.16.1
  - npm version: 6.13.4
  - `@google-cloud/automl` version: v1

#### Steps to reproduce

  1. 
```
function createAutoMLDataset() {

  return new Promise((resolve, reject) => {
    const request = {
      parent: automlClient.locationPath(projectId, location),
      dataset: {
        displayName: dataset_id,
        imageObjectDetectionDatasetMetadata: {}
      }
    };

    automlClient
      .createDataset(request)
      .then(responses => {
        console.log("[createAutoMLDataset] response", responses);
        resolve(responses);
      })
      .catch(err => {
        reject(`error occurred dataset: ${err}`);
      });
  });
}
```
  2.
```
     createAutoMLDataset()
          .then(datasetResp => {
            console.log("[datasetResp]", datasetResp);
            automlDatasetId = datasetResp[0].name.split("/")[
              datasetResp[0].name.split("/").length - 1
            ];
            console.log("[autoML datasetId]:", automlDatasetId);
            return uploadToAutoML(
              `gs://${bucketName}/${model_prefix}/test.csv`,
              automlDatasetId
            );
          }) 
```
Best.

**Comment by bcoe** [comment]
@nnegrey any thoughts on this one?

**Comment by nnegrey** [comment]
I believe you want to take a look at this sample. https://github.com/googleapis/nodejs-automl/blob/master/samples/vision_object_detection_create_dataset.js

Which parses the `datasetId` out like this
`response.name.split('/')[response.name.split('/').length - 1].split('\n')[0]`

**Comment by SanyapongYoukachen** [comment]
I look at that sample already, but i get unexpected response from createDataset as followed 1.). It is array of [Opration, object, null] with the same "name": "projects/xxx/locations/us-central1/operations/IODxxx" in operation and object.

So i always got TypeError: Cannot read property 'split' of undefined, when i used 
response.name.split('/')[response.name.split('/').length - 1].split('\n')[0], when i followed the sample.

Therefore, i adapted code as metioned and it works just fine previously. Only now the datasetId from library is mismatched the actual datasetId, Any update with the library?.

1.) 
[ Operation {
    domain: 
     Domain {
       domain: null,
       _events: [Object],
       _eventsCount: 1,
       _maxListeners: undefined,
       members: [Array] },
    _events: { newListener: [Function], removeListener: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    completeListeners: 0,
    hasActiveListeners: false,
    latestResponse: 
     { name: 'projects/xxx/locations/us-central1/operations/xxx',
       metadata: [Object],
       done: false },
    name: 'projects/xxx/locations/us-central1/operations/xxx',
    done: false,
    error: undefined,
    longrunningDescriptor: 
     LongRunningDescriptor {
       operationsClient: [Object],
       responseDecoder: [Function: bound decode_setup],
       metadataDecoder: [Function: bound decode_setup] },
    result: null,
    metadata: 
     OperationMetadata {
       partialFailures: [],
       createTime: [Object],
       updateTime: [Object],
       createDatasetDetails: CreateDatasetOperationMetadata {} },
    backoffSettings: 
     { initialRetryDelayMillis: 100,
       retryDelayMultiplier: 1.3,
       maxRetryDelayMillis: 60000,
       initialRpcTimeoutMillis: null,
       rpcTimeoutMultiplier: null,
       maxRpcTimeoutMillis: null,
       totalTimeoutMillis: null },
    _callOptions: 
     CallSettings {
       timeout: 5000,
       retry: [Object],
       autoPaginate: true,
       pageToken: undefined,
       maxResults: undefined,
       otherArgs: [Object],
       bundleOptions: null,
       isBundling: true,
       longrunning: undefined,
       promise: [Function: Promise] } },
  { name: 'projects/xxx/locations/us-central1/operations/xxx',
    metadata: 
     { type_url: 'type.googleapis.com/google.cloud.automl.v1.OperationMetadata',
       value: <Buffer 1a 0c 08 bd d2 fa f3 05 10 e8 cb 94 ca 03 22 0c 08 bd d2 fa f3 05 10 e8 cb 94 ca 03 f2 01 00> },
    done: false },
  null ]

**Comment by SanyapongYoukachen** [comment]
Now, I used your sample code and it works very robustly. Seem like the problem is on me. Sorry for annoying and thank you very much for the good library and great response.

Best.
