### ISSUE TITLE
NOT_FOUND: Invalid resource ID when calling Custom Model From Firebase Function

### ISSUE THREAD

**Issue by matt7tt** [googleapis/nodejs-automl#389]
I'm calling a GCP Custom ML Model from a node.js 8 firebase function. But when I call the predict function, I get an Error 5: NOT_FOUND: Invalid resource ID I've turned on the ML API and I've checked the format of the model name, it looks to be correct according to the docs: projects/<project-id>/locations/us-central1/models/<model-name>

My code looks like:

// Create client for prediction service.
const client = new automl.PredictionServiceClient();

const projectId = 'project-id';
const computeRegion = 'us-central1';
const modelId = 'model-name';

// Get the full path of the model.
const modelFullId = client.modelPath(projectId, computeRegion, modelId);

const params = {};
const payload = {};
payload.instances = {"data1": 38.0,
                     "data2": -2.7,
                     "data3": -0.4,
                     "data4": 2.1,
                     "data5": -2.7,
                     "data6": -1.7,
                     "data7": 0.4,
                     "data8": 8.5,
                     "data9": -1.1,
                     "data10": 0.2
                    };

const [response] = await client.predict({
                        name: modelFullId,
                        payload: payload,
                        params: params,
                    });
console.log(`Prediction results:`);
response.payload.forEach(result => {
    console.log(`Predicted class name: ${result.displayName}`);
    console.log(`Predicted class score: ${result.classification.score}`);
});

Thanks for your help.

**Comment by Rohed** [comment]
Having the same issue except using:

const modelId = 'FICNXXXX...';

**Comment by kweinmeister** [comment]
Since we haven't heard any response, we'll go ahead and close this issue. Please feel free to reopen if you have any updates.
