### ISSUE TITLE
predict allows max 1 value but sample implies >1 value is allowed

### ISSUE THREAD

**Issue by marcusgreenwood** [googleapis/nodejs-automl#405]
https://github.com/googleapis/nodejs-automl/blob/632d7e311052e9086b4152bf6df01f20eea68993/samples/tables/predict.v1beta1.js#L53

This has been confusing me for hours. The sample reads data from a CSV, which kind of implies multiple values, but when attempting to predict with multiple row values it throws the error 
`Error: 3 INVALID_ARGUMENT: Expected 1 values, got 3.`

**Comment by munkhuushmgl** [comment]
@marcusgreenwood Could you share your .csv file and what dataset you have trained on?

**Comment by marcusgreenwood** [comment]
It's an internal one that we're using that I've trained using 2 columns (text and category). We want to run circa 100 predictions concurrently and have had to use `Promise.all` to do this – which works fine, but looking at your sample, I had assumed I could simply send them all in a single POST http request.

**Comment by munkhuushmgl** [comment]
@marcusgreenwood I will inform this to my team, and will request the changes.

It will probably take a while to push the changes. I will tag you in the PR.

**Comment by marcusgreenwood** [comment]
Thanks.

**Comment by telpirion** [comment]
I created a public issue on the issue tracker for this request:
https://issuetracker.google.com/issues/160624273
