### ISSUE TITLE
model-id is not returned for finished operation in the response of the getOperation.   

### ISSUE THREAD

**Issue by lisenkaci** [googleapis/nodejs-automl#428]
I am trying to get the model-id of a completed operation using the operationId. the snippet of me call:  
```
    const request = {
    name: `projects/${projectId}/locations/${location}/operations/${operationId}`,
    };
  
    const [response] = await client.operationsClient.getOperation(request); 
    console.log(`Name: ${response.name}`);
    console.log(`Operation details:`);
    console.log(`${JSON.stringify(response, null, 2)}`);
```

my response:
```
{
  "name": "projects/projectId/locations/us-central1/operations/operationId”,
  "metadata": {
    "type_url": "type.googleapis.com/google.cloud.automl.v1.OperationMetadata",
    "value": {
      "type": "Buffer",
      "data": […]
    }
  },
  "done": true,
  "response": {
    "type_url": "type.googleapis.com/google.cloud.automl.v1.Model",
    "value": {
      "type": "Buffer",
      "data": […]
    }
  },
  "result": "response"
}

```

If done is true the response.response should contain name which has the model-id in it. My operation is done but no model-id! the model has finished training and is in my dashboard correctly. I need to get the modelId programatically though!

Thank you for your help.

**Comment by munkhuushmgl** [comment]
@lisenkaci Have you got a chance to look at this stackoverflow answer?
https://stackoverflow.com/questions/60748968/how-to-programmatically-get-model-id-from-google-cloud-automl-with-node-js-clien

**Comment by lisenkaci** [comment]
Yes I have seen that answer. Unfortunately my response does not match the one returned there or in the docs. Even though I have the "done" field as "true" I am not getting the  "response.response" object which has the "name" field that contains the model-Id in it.

**Comment by munkhuushmgl** [comment]
@lisenkaci okay, I will try to reproduce this error on my end, and If I get the same error, I will log a bug on AutoML API.

**Comment by lisenkaci** [comment]
I finally figured this one out! It was returning the name with the model-Id in it as a Buffer inside the "value" 🤷. 
In order to extract the model-Id I had to do 

`const modelId = response.response.value.toString('utf8').replace(/projects\/[a-zA-Z0-9-]*\/locations\/[a-zA-Z0-9-]*\/models\//,'');`

**Comment by munkhuushmgl** [comment]
I was trying to convert that buffer into simple string format. glad you found out on your own

Thanks for sharing your solution
