### ISSUE TITLE
Not possible to get operation status.

### ISSUE THREAD

**Issue by farandal** [googleapis/nodejs-automl#433]
#### Environment details

  - OS: MacOS Catalina 10.15.6
  - Node.js version: 12.8.1
  - npm version: 6.14.15
  - `@google-cloud/automl` version: 2.2.0, using v1alpha1
  -  "tsc": "^1.20150623.0",
  -  "typescript": "^3.8.3",

#### Typescript config

{
  "compilerOptions": {
   ...
    "noImplicitAny": false,
    "target": "es6",
    "moduleResolution": "node",
    "lib": ["es6", "dom"],
    "allowJs": false,
    "module": "esnext",
    "sourceMap": true,
    "jsx": "react",
    ...
  },

#### Steps to reproduce

1.- Starting point:
     https://github.com/googleapis/nodejs-automl/blob/master/samples/beta/get-operation-status.js

2.- Sample Implementation throws TS warnings, therefore I implemented the corresponding types. 
*TS complains about a missing name property
*TS complains about the lack of toJSON property in object. 

```
 public operationStatus = async (operationId: string) => {
    
    const request: google.longrunning.GetOperationRequest = new google.longrunning.GetOperationRequest(
      {
        'name' : `projects/${this.credentials.projectId}/locations/${this.settings.location}/operations/${operationId}`
      }
    );

    const [response] = await this.client.operationsClient.getOperation(request);

    return response;
  };
```

3.- On a recently deploy model action triggered, I try to get the status update on the deployment, sending the correct operationID. Nevertheless, the client.getOperation method keeps throwing a server error.
Code execution throws: missing name Field: name.

**Comment by munkhuushmgl** [comment]
I can take this @telpirion feel free to unassign yourself.

**Comment by munkhuushmgl** [comment]
@farandal I have very small knowledge on Typescript, but looks like your API request not formatted in right way.
Maybe something with single quote on 'name'
```
  'name' : `projects/${this.credentials.projectId}/locations/${this.settings.location}/operations/${operationId}`
```

**Comment by munkhuushmgl** [comment]
Due to inactivity, I am closing this issue.

Feel free to reopen this if you still having isse
