### ISSUE TITLE
test: list_operation_status.test.js is being skipped

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-automl#440]
The`list_operation_status.test.js` is failing with a buffer error (_this is most likely a memory issue_).

I am skipping the test so that we can get `.kokoro` updated to Node 12, and the majority of the test suite running again.

see: https://github.com/googleapis/nodejs-automl/pull/439/files#diff-8f06dfd57d65f8865cbb2e08552c12b4

**Comment by munkhuushmgl** [comment]
It should be fixed by now since we cleaned up designated GCP
