### ISSUE TITLE
How to publish model with node? 

### ISSUE THREAD

**Issue by followthemoney1** [googleapis/nodejs-automl#475]
Hey everyone, how can I publish the model not using the firebase UI but using the code?
I'm already create a client witch fill and predicts my model using node.js. And from my client application I'm receiving my model by name like this:
```
 let remoteModel = AutoMLImageLabelerRemoteModel(
       // name: "training_model"  // The name you assigned in
        name:"v20201209133002"
        // the Firebase console.
    )
...
if (ModelManager.modelManager().isModelDownloaded(remoteModel)) {
            options = AutoMLImageLabelerOptions(remoteModel: remoteModel)
            options!.confidenceThreshold = NSNumber(value: PRECOGNITION_PERSENTAGE)
            self.imageLabeler = ImageLabeler.imageLabeler(options: options!)
            onSuccess()
        } else {
...
```
From firebase UI to publish already trained model I can do something like:

![image](https://user-images.githubusercontent.com/8526612/101654237-f35dd000-3a48-11eb-86e1-134208518b75.png)

![image](https://user-images.githubusercontent.com/8526612/101654219-eb9e2b80-3a48-11eb-85f0-79055533ae7c.png)

But how can I do the same with node or phyton? Any help?

**Comment by munkhuushmgl** [comment]
@followthemoney1 
```
// First, import and initialize the SDK as shown above.

(async () => {
  // Upload the tflite file to Cloud Storage
  const storageBucket = admin.storage().bucket('your-storage-bucket');
  const files = await storageBucket.upload('./example.tflite');

  // Create the model object and add the model to your Firebase project.
  const bucket = files[0].metadata.bucket;
  const name = files[0].metadata.name;
  const gcsUri = `gs:/⁠/${bucket}/${name}`;
  const model = await ml.createModel({
    displayName: 'example_model',  // This is the name you use from your app to load the model.
    tags: ['examples'],  // Optional tags for easier management.
    tfliteModel: { gcsTfliteUri: gcsUri },
  });

  // Publish the model.
  await ml.publishModel(model.modelId);

  process.exit();
})().catch(console.error);
```

**Comment by munkhuushmgl** [comment]
that was just example with TensorFlow Lite

**Comment by munkhuushmgl** [comment]
For full documentation:

https://firebase.google.com/docs/ml/manage-hosted-models#node.js

**Comment by followthemoney1** [comment]
@munkhuushmgl but it's for a custom tensorflow model or isn't it?

**Comment by followthemoney1** [comment]
Thanks @munkhuushmgl for the answer. But when I'm trying to publish my automl model from docs:
```const automlModel = `projects/${projectNumber}/locations/${storageLocation}/models/${modelId}`;

  // Create the model object and add the model to your Firebase project.
  const model = await ml.createModel({
    displayName: 'example_model',  // This is the name you use from your app to load the model.
    tags: ['examples'],  // Optional tags for easier management.
    tfliteModel: { automlModel: automlModel },
  });

  // Wait for the model to be ready.
  await model.waitForUnlocked();

  // Publish the model.
  await ml.publishModel(model.modelId);```

**Comment by munkhuushmgl** [comment]
Hmm, I will try to reproduce your error.
Meanwhile, Can you share error stacktrace?

**Comment by followthemoney1** [comment]
And by the way, when I'll try to upload an already existing model I got and error:
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/8526612/101804079-dd6c1000-3b19-11eb-81c8-34cfc9137d1d.png">


I can share a project if need, or another code. Just ask)

**Comment by followthemoney1** [comment]
this one?
when try upload with automl
```
Error: You do not have permission to export the AutoML model. at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28) at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28) at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23) at Function.FirebaseMachineLearningError.fromOperationError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:43:28) at MachineLearningApiClient.handleOperation (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:164:81) at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning.js:87:62 at process._tickCallback (internal/process/next_tick.js:68:7)
Error: You do not have permission to export the AutoML model. at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28) at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28) at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23) at Function.FirebaseMachineLearningError.fromOperationError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:43:28) at MachineLearningApiClient.handleOperation (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:164:81) at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning.js:87:62 at process._tickCallback (internal/process/next_tick.js:68:7)
```

when try upload with custom.tflite
```
 Error: Unable to process TFLite File. at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28) at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28) at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23) at Function.FirebaseMachineLearningError.fromOperationError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:43:28) at MachineLearningApiClient.handleOperation (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:164:81) at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning.js:87:62 at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Unable to process TFLite File. at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28) at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28) at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23) at Function.FirebaseMachineLearningError.fromOperationError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:43:28) at MachineLearningApiClient.handleOperation (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:164:81) at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning.js:87:62 at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by munkhuushmgl** [comment]
> this one?
> when try upload with automl
> 
> ```
> Error: You do not have permission to export the AutoML model. at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28) at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28) at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23) at Function.FirebaseMachineLearningError.fromOperationError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:43:28) at MachineLearningApiClient.handleOperation (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:164:81) at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning.js:87:62 at process._tickCallback (internal/process/next_tick.js:68:7)
> Error: You do not have permission to export the AutoML model. at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28) at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28) at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23) at Function.FirebaseMachineLearningError.fromOperationError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:43:28) at MachineLearningApiClient.handleOperation (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:164:81) at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning.js:87:62 at process._tickCallback (internal/process/next_tick.js:68:7)
> ```
> 
> when try upload with custom.tflite
> 
> ```
>  Error: Unable to process TFLite File. at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28) at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28) at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23) at Function.FirebaseMachineLearningError.fromOperationError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:43:28) at MachineLearningApiClient.handleOperation (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:164:81) at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning.js:87:62 at process._tickCallback (internal/process/next_tick.js:68:7)
> Error: Unable to process TFLite File. at FirebaseMachineLearningError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:43:28) at FirebaseMachineLearningError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:89:28) at new FirebaseMachineLearningError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:37:23) at Function.FirebaseMachineLearningError.fromOperationError (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-utils.js:43:28) at MachineLearningApiClient.handleOperation (/workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js:164:81) at /workspace/node_modules/firebase-admin/lib/machine-learning/machine-learning.js:87:62 at process._tickCallback (internal/process/next_tick.js:68:7)
> ```

from this, Looks like its permission issue. Did you make sure your service account or your authentication have sufficient permission to publish model?

**Comment by followthemoney1** [comment]
@munkhuushmgl which I miss, from the screenshot you can saw  that I'm already owner and MlAdmin. What resolution are you talking about or where maybe I can see them? Wtf the strange response 🤯😁

**Comment by followthemoney1** [comment]
@munkhuushmgl sorry, thanks for the help. Fixed when adding automl admin permission to the service account:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/8526612/101843456-e4fbdb00-3b52-11eb-831f-e553d401afcb.png">
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/8526612/101843498-ffce4f80-3b52-11eb-947f-cd24a1042521.png">
