### ISSUE TITLE
Can't send null on optional fields

### ISSUE THREAD

**Issue by wololodev** [googleapis/nodejs-automl#571]
I trained a model using Automl Tables with a dataset that had an optional feature (column). In the sample file it doesn't show how to deal with optional fields.

```javascript
  // Set the payload by giving the row values.
  const payload = {
    row: {
      values: [
        {
          numberValue: 1, // amntOfNights
        },
        {
          stringValue: 'CA', // userCountry
        },
        {
          numberValue: null, // distanceUserFromVenue
        },
        {
          stringValue: 'desktop', // device
        }
      ],
    },
  };

  // Params is additional domain-specific parameters.
  // Currently there is no additional parameters supported.
  const [response] = await clientML.predict({
    name: top11,
    payload: payload,
    params: { feature_importance: false },
  });
```

```
[SERVER] Error: 3 INVALID_ARGUMENT: Cannot parse ProtoValue kind Unknown as FLOAT64.; Error parsing FLOAT64 value; Error parsing ProtoValue for column: distanceUserFromVenue
[SERVER]     at Object.callErrorFromStatus (/Users/hamed/www/frontend/node_modules/@google-cloud/automl/node_modules/@grpc/grpc-js/src/call.ts:81:24)
[SERVER]     at Object.onReceiveStatus (/Users/hamed/www/frontend/node_modules/@google-cloud/automl/node_modules/@grpc/grpc-js/src/client.ts:343:36)
[SERVER]     at Object.onReceiveStatus (/Users/hamed/www/frontend/node_modules/@google-cloud/automl/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
[SERVER]     at Object.onReceiveStatus (/Users/hamed/www/frontend/node_modules/@google-cloud/automl/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
[SERVER]     at /Users/hamed/www/frontend/node_modules/@google-cloud/automl/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
[SERVER]     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
[SERVER]   code: 3,
[SERVER]   details: 'Cannot parse ProtoValue kind Unknown as FLOAT64.; Error parsing FLOAT64 value; Error parsing ProtoValue for column: distanceUserFromVenue',
[SERVER]   metadata: Metadata {
[SERVER]     internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
[SERVER]     options: {}
[SERVER]   }
[SERVER] }
```

I don't always have a value for this numeric field `numberValue: distanceUserFromVenue`, I looked around and tried some stuff but no luck!

**Comment by galz10** [comment]
I can't be much of an assistance without having the model but my guess is that if the `distanceUserFromVenue` is null it shouldn't be in the payload. So try having a if statement that either has a payload with `distanceUserFromVenue` or without depending if `distanceUserFromVenue` is null

**Comment by wololodev** [comment]
If it's not in the payload then the order of the array payload gets scuffed, where as it's expecting `distanceUserFromVenue` at that array position. This would probably work if it was key-value payload but not with v1beta sdk

**Comment by galz10** [comment]
Yea looking at the reference document it seems like null should work fine, i'll investigate this further. Could you try using google.protobuf.NullValue instead of null.

**Comment by wololodev** [comment]
thanks gal, we're not using protobufs and it look like it requires some preparation to get it running. In the meantime we're sending `0` as the value instead of `null` but that definently could skew the prediction as `0` is valid

**Comment by dizcology** [comment]
@wololodev instead of `numberValue: null`, please use protobuf's NullValue for that column: https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#nullvalue
